[env]
LVE = "12f5697c-1c4e-498c-91b9-e43119a273dc"
WALLET = "~/.config/solana/"

DN_PROGRAM_DEVNET = "9YmDSZaTX5ALSvrQiuE2vuztESzJGX97tEYLngTR3GXz"
DN_NETWORK_DEVNET = "https://api.devnet.solana.com"
DN_CLUSTER_DEVNET = "devnet"

VT_PROGRAM_DEVNET = ""
VT_NETWORK_DEVNET = "https://api.apr.dev"
VT_CLUSTER_DEVNET = "devnet"

