[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
vaulted = "ACgeeZmREHqAXoSgvCjot191Y4Vbpzuguw1pHgVeDzDv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
init = "cargo run --bin init"
