[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
datanode = "9YmDSZaTX5ALSvrQiuE2vuztESzJGX97tEYLngTR3GXz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
