[[transactions]]

[transactions.signature]
tx_00 = "9UK2xaCbNKJz7cFKxH7Z8hrbrrwGB8HKgoZD5C5tRmKawRHMzGv3kLZEjxf4qG1UWJpGofKGpNRoapRqSNJ9BTA"
tx_01 = "5zoKK2hegr69Ttg5E7PbCPBYT8vaL4f6N53SgtGu76Fuf5xbV7WsPonfqHzCZsu2TTmTYh97rrm1TiWVTJ9SRby3"

[transactions.block]
tx_00 = 321957340
tx_01 = 321484751

[transactions.signer]
tx_00 = "C4nYJX8RS9PwNZt3UywgbWSTMePAXTWSJELpQU1Y9k8T"
tx_01 = "7dGrdJRYtsNR8UYxZ3TnifXGjGc9eRYLq9sELwYpuuUu"

