[[raydimum]]

WSOL_VINE = "58fzJMbX5PatnfJPqWWsqkVFPRKptkbb5r2vCw4Qq3z9"
WSOL_HOGFROG = "3gMim3PSpJTj1rcdFTyaEYSFbdA6ccc1s14PTT5gcuZo"
WSOL_USDC = "58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2"
WSOL_FWOG = "AB1eu2L1Jr3nfEft85AuD2zGksUbam1Kr8MR3uM2sjwt"
WSOL_NUIT = "966sLyXCxj1HedfdFQsv2LiNHUaUhMNadBcD4kDcJ1MP"

[[orca]]

WSOL_USDC = "Czfq3xZZDmsdGdUyrNLtRhGc47cXcZtLG4crryfu44zE"
WSOL_UFD = "4m72fcieYpvtrwNw5RkBsGKmgA2un7vu7PARrQCSBTzy"
WSOL_JUPSOL = "DtYKbQELgMZ3ihFUrCcCs9gy4djcUuhwgR7UpxVpP2Tg"

[[meteora]]

SSS_SOL = "6vUZdVmSFrxvQqBUHr9DUcs5ZiNQGitToWntnon3o9hF"
M3M3_WSOL = "4FL43x2QRGmt8pSjD1YERwMv7gfT2DQwby5yikvVi23X"

