[package]
name = "ix-composer"
publish = false
readme = "README.md"
version = "0.0.1"
rust-version = "1.84.1"
edition = "2021"
authors = ["palisade research ltd"]

[dependencies]
ix-results = { path = "../ix-results", version = "0.0.1" }

