services:
  clickhouse:
      build:
        context: .
        dockerfile: clickhouse.Dockerfile
      ports:
        - "8123:8123"
        - "9000:9000"
      volumes:
        - clickhouse_data:/var/lib/clickhouse
        - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
        - ./clickhouse/users.xml:/etc/clickhouse-server/users.xml
      environment:
        - CLICKHOUSE_DB=default
        - CLICKHOUSE_USER=default
        - CLICKHOUSE_PASSWORD=
        - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      ulimits:
        nofile:
          soft: 262144
          hard: 262144
      healthcheck:
        test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
        interval: 30s
        timeout: 10s
        retries: 3
      command: >
        sh -c "
          rm -f /etc/clickhouse-server/users.d/default-password.xml &&
          /entrypoint.sh
        "

volumes:
  clickhouse_data:
