# Fixed docker-compose.yml with correct paths
version: '3.8'
services:

  database:
    build:
      context: .
      dockerfile: dataplatform/database/build/database.Dockerfile
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - database_data:/var/lib/clickhouse
      - ./dataplatform/database/configs/config.xml:/etc/clickhouse-server/config.xml
      - ./dataplatform/database/configs/users.xml:/etc/clickhouse-server/users.xml
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - datalake-network

  datacollector:
    build:
      context: .
      dockerfile: dataplatform/datacollector/build/datacollector.Dockerfile
    depends_on:
      database:
        condition: service_healthy
        restart: true
    environment:
      - RUST_LOG=info
      - CLICKHOUSE_URL=http://database:8123
    volumes:
      - ./logs:/app/logs
    ports:
      - "9009:9009"
    healthcheck:
      test: ["CMD", "pgrep", "collector"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - datalake-network

volumes:
  database_data:

networks:
  datalake-network:
    driver: bridge
