[exchange]
name = "binance"
base_url = "https://api.binance.com"
api_version = "v3"

[api]
# Public market data endpoints don't require authentication
# For authenticated calls (if needed later)
# api_key = "your_api_key"
# api_secret = "your_api_secret"

[pairs]
symbols = ["BTCUSDT", "ETHUSDT", "SOLUSDT"]

[collection]
interval_seconds = 1
retry_attempts = 3
timeout_seconds = 10
# Binance rate limit: 1200 requests per minute

[database]
hosts = ["scylladb:9042"]
keyspace = "orderbook_data"
table = "binance_orderbooks"

[logging]
level = "info"
file = "/var/log/binance_client.log"
