[exchange]
name = "bybit"
base_url = "https://api.bybit.com"
api_version = "v5"
wss_public_url = "wss://stream.bybit.com/v5/public"
wss_private_url = "wss://stream.bybit.com/v5/private"
testnet_url = "testnet"

[api]
api_key = "eEmQIB8BV1rMjdqHnC" # "nHMnnRmoUo1uInJthY"
api_secret = "ztZkrq0GUySr5ERCGXwAAKXam8GxGIsdfbww" # "xgbVoVIigdgs9Epvs9XCxUT5vD2e4WQm4TZj"
recv_window = 6000
testnet = false

[pairs]
symbols = ["SOLUSDT"]

[streams]
orderbooks = ["orderbook.25.SOLUSDC_SOL/USDC",
              "orderbook.25.BTCUSDC_BTC/USDC"]

publictrades = ["publicTrade.SOLUSDC_SOL/USDC",
                "publicTrade.BTCUSDC_BTC/USDC"]

[collection]
interval_seconds = 1
retry_attempts = 3
timeout_seconds = 10

[database]
hosts = ["localhost:8123"]
database = "cex"
table = "bybit_orderbooks"

[logging]
level = "info"
file = "/var/log/bybit_client.log"
