[exchange]
name = "coinbase"
base_url = "https://api.coinbase.com"

api_version = "v3"

# [api]
# api_key = "none"
# api_secret = "none"
# passphrase = "none"

[pairs]
symbols = ["BTC-USD", "ETH-USD", "SOL-USD"]

[collection]
interval_seconds = 1
retry_attempts = 3
timeout_seconds = 10

[database]
hosts = ["localhost:8123"]
database = "cex"
table = "coinbase_orderbooks"

[logging]
level = "info"
file = "/var/log/coinbase_client.log"
