[exchange]
name = "kraken"
base_url = "https://api.kraken.com"
api_version = "0"

[api]
# Public endpoints don't require authentication
# For authenticated calls (if needed later)
# api_key = "your_api_key"
# api_secret = "your_api_secret"

[pairs]
# Kraken uses different pair naming
symbols = ["XBTUSD", "ETHUSD", "SOLUSD"]

[collection]
interval_seconds = 1
retry_attempts = 3
timeout_seconds = 10
# Kraken rate limit: 1 request per second for public endpoints

[database]
hosts = ["scylladb:9042"]
keyspace = "orderbook_data"
table = "kraken_orderbooks"

[logging]
level = "info"
file = "/var/log/kraken_client.log"
